[package]
name = "RESTfulAPI-v2-SqliteDb"
version = "0.1.0"
edition = "2021"

[lints.rust]
unused_imports = "allow"

[dependencies]
actix-web = "4.3.1"
rusqlite = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
